### ISSUE TITLE
Find the way to get rid of duplicating blocks in ansbile playbooks 

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud-infra/customer-service-monitoring#106]

**Comment by anton-sidelnikov** [comment]
look at: https://docs.ansible.com/ansible/latest/modules/include_vars_module.html

**Comment by anton-sidelnikov** [comment]
block: 
    telegraf_influxdb_urls:
      - https://influx1.eco.tsi-dev.otc-service.com:8086
    telegraf_influxdb_database: csm
    telegraf_influxdb_username: csm
    telegraf_influxdb_password: "{{ lookup('env', 'INFLUX_PSWD') }}"

in
scenario1_setup.yml
scenario1_setup_telegraf_only.yml
scenario2_setup.yml
scenario3_setup.yml
scenario4_image_setup.yml
