### ISSUE TITLE
Check if `csm` influx user can control its own data retention policy

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud-infra/customer-service-monitoring#170]
CSM user produces a lot of data, so data retention policy should be more strict for it (1 mnth of a/s data consume > 2G memory, crashes influx container, crashes podman)

**Comment by anton-sidelnikov** [comment]
fixed in https://github.com/opentelekomcloud-infra/myndir/pull/2, in next scenarios this problem shouldn appear
