### ISSUE TITLE
Find additional metrics for existing scenarios

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud-infra/customer-service-monitoring#220]

**Comment by anton-sidelnikov** [comment]
https://github.com/opentelekomcloud-infra/delatore/issues/86
https://github.com/opentelekomcloud-infra/delatore/issues/88
https://github.com/opentelekomcloud-infra/delatore/issues/89
https://github.com/opentelekomcloud-infra/delatore/issues/90
https://github.com/opentelekomcloud-infra/delatore/issues/91
https://github.com/opentelekomcloud-infra/delatore/issues/92
