### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by anton-sidelnikov** [opentelekomcloud-infra/customer-service-monitoring#247]
Update project to easy extend scenarios count.
Try to use one bastion for all scenarios. #212 

- [x] #251 
- [x] #252
- [x] #255 
- [x] #256
- [x] #263
- [x] #267 
- [x] #272 
- [x] #279
- [x] #280
- [x] #281

Zuul CI as main CI/CD
- [x] #266

**Comment by lego963** [comment]
All tasks have been resolved
